<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>CsfleDemo.Shared</RootNamespace>
    <AssemblyName>CsfleDemo.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
  </ItemGroup>

</Project>
