---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: url
        url:
          - name: kafka-connect-jdbc # the url is used here as we needed to build our own connector lib to include the mysql jdbc jar
            archivePath: https://raw.githubusercontent.com/pneff93/csfle/connect/azure_connect/confluentinc-kafka-connect-jdbc-10.8.4.zip
            checksum: 37f383cd44e456c22d96ef23ae4bbac85e33bf73669cb5d8fcce0e87345c092e88f2be5cc97b03f64d301c1c5f96fecf18d9d0f6f2a5db4062816597fa9a0b0b
  dependencies:
    kafka:
      bootstrapEndpoint: pkc-5roon.us-east-1.aws.confluent.cloud:9092
      authentication:
        type: plain
        jaasConfig:
          secretRef: ccloud-credentials
      tls:
        enabled: true
        ignoreTrustStoreConfig: true
    schemaRegistry:
      url: https://psrc-k6gvm.us-west-2.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials
  mountedSecrets:
  - secretRef: mysql-credential